INSERT INTO BEER (NAME, PRICE_PER_LITRE) values ('Corona', 2);
INSERT INTO PROMOTER (NAME, ACTIVE) values ('Rohit Gupta', true);
INSERT INTO ATTENDEE (NAME) values ('Megha Mittal');
INSERT INTO ADMIN (NAME) values ('Master');
INSERT INTO TAP (NAME, FLOW_PER_SECOND, BEER_ID, PROMOTER_ID) values ('Big Tap', 1.2, 1, 1);
INSERT INTO SERVING (FLOW_PER_SECOND, PRICE_PER_LITRE, START_TIME, END_TIME, TOTAL, BEER_ID, TAP_ID, PROMOTER_ID, ATTENDEE_ID) values (1.2, 2, CURRENT_DATE, DATEADD(DAY, -1, CURRENT_DATE) + TIME '10:50:00', 20.5, 1, 1, 1, 1);